name: Android CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Remove old keystore if exists
        run: rm -f mybudget.keystore

      - name: Create keystore from secret
        run: echo "${{ secrets.SIGNING_KEY }}" | base64 -d > mybudget.keystore

      - name: Show keystore file info
        run: ls -lh mybudget.keystore

      - name: Debug keystore password
        run: |
          echo "First 2 chars of KEY_STORE_PASSWORD: ${KEY_STORE_PASSWORD:0:2}"
          echo "Length of KEY_STORE_PASSWORD: ${#KEY_STORE_PASSWORD}"
        env:
          KEY_STORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          android-sdk: '34'
          build-tools: '34.0.0,29.0.3'

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/cache
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Create Lint Baseline
        continue-on-error: true
        run: ./gradlew lintDebug

      - name: Run tests
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Build Release APK
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > mybudget.keystore
          echo "Current directory: $(pwd)"
          echo "Listing current directory:"
          ls -la
          echo "Keystore file details:"
          ls -la mybudget.keystore
          echo "Keystore file created at: $(pwd)/mybudget.keystore"
          echo "Checking keystore contents:"
          keytool -list -v -keystore mybudget.keystore -storepass "${{ secrets.KEY_STORE_PASSWORD }}" || echo "Keystore validation failed"
          echo "Verifying keystore password:"
          if keytool -list -v -keystore mybudget.keystore -storepass "${{ secrets.KEY_STORE_PASSWORD }}" > /dev/null 2>&1; then
            echo "Keystore password is correct"
          else
            echo "Keystore password is incorrect"
            exit 1
          fi
          echo "Running Gradle with debug info:"
          ./gradlew assembleRelease \
            -PkeystorePassword="${{ secrets.KEY_STORE_PASSWORD }}" \
            -PkeyAlias="${{ secrets.KEY_ALIAS }}" \
            -PkeyPassword="${{ secrets.KEY_PASSWORD }}" \
            --stacktrace --info

      - name: Get version name
        id: get_version
        run: echo "VERSION=$(./gradlew properties -q | grep 'versionName:' | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: app/build/outputs/apk/release/app-release.apk

  release:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get version name
        id: get_version
        run: echo "VERSION=$(./gradlew properties -q | grep 'versionName:' | awk '{print $2}')" >> $GITHUB_OUTPUT

      - name: Download Release APK
        uses: actions/download-artifact@v4
        with:
          name: app-release

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: Release v${{ steps.get_version.outputs.VERSION }}
          body: |
            # 🇷🇺 Русский

            ## 🚀 Новый релиз v${{ steps.get_version.outputs.VERSION }}

            ### 📱 Способы установки
            #### Официальные магазины
            - [RuStore](https://www.rustore.ru/catalog/app/ru.iuturakulov.mybudget) - Уже доступно!
            - Google Play - Скоро!

            #### Прямая установка
            Вы также можете установить APK напрямую из этого релиза:
            1. Скачайте APK из раздела "Assets" ниже
            2. Установите на ваше Android-устройство
            3. Наслаждайтесь новой версией!

            ### 🔍 Информация о версии
            - Версия: ${{ steps.get_version.outputs.VERSION }}
            - Дата сборки: ${{ github.event.repository.updated_at }}
            - Коммит: ${{ github.sha }}

            ### 📝 Примечания к релизу
            ${{ github.event.head_commit.message }}

            ---

            # 🇬🇧 English

            ## 🚀 New Release v${{ steps.get_version.outputs.VERSION }}

            ### 📱 Способы установки
            #### Официальные магазины
            - [RuStore](https://www.rustore.ru/catalog/app/ru.iuturakulov.mybudget) - Уже доступно!
            - Google Play - Скоро!

            #### Прямая установка
            Вы также можете установить APK напрямую из этого релиза:
            1. Скачайте APK из раздела "Assets" ниже
            2. Установите на ваше Android-устройство
            3. Наслаждайтесь новой версией!

            ### 🔍 Информация о версии
            - Версия: ${{ steps.get_version.outputs.VERSION }}
            - Дата сборки: ${{ github.event.repository.updated_at }}
            - Коммит: ${{ github.sha }}

            ### 📝 Примечания к релизу
            ${{ github.event.head_commit.message }}
          files: app-release-signed.apk
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 